# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UberTutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UberTutorial

  pod 'SnapKit', '~> 5.0.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'GeoFire', '>= 1.1'

end
